// <auto-generated />
namespace BackstageMusic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addadmintoscheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addadmintoscheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201911212303181_add-admin-to-scheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
