// <auto-generated />
namespace BackstageMusic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_user_structure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_user_structure));
        
        string IMigrationMetadata.Id
        {
            get { return "201911062333033_change_user_structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
